name: E2E on Chrome

on: [push]
  
jobs:
  install:
    runs-on: ubuntu-latest
    env:
         PR_NUMBER: ${{ github.event.pull_request.number }}
         run: |
         curl -H "Authorization: token ${{ secrets.GIT_TOEKN }}" -X POST -d '{"assignees":["siam1113"]}' https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: npm run dev
         
